"""
test_news_database.py
-------------------------
Unit tests for Database v1 (news_database.py).

TESTING STRATEGY:
Every test uses an IN-MEMORY SQLite database (db_path=":memory:") — no
files touch disk, tests are fast and fully isolated from each other and
from any real Google Drive path. This is the exact same code path used
in Colab with a real file path; only the location differs.
"""

import os
import json
import tempfile
import unittest
from datetime import datetime, timedelta, timezone

from news_database import NewsDatabase


def make_article(**overrides):
    base = {
        "article_id": "id-0",
        "url": "https://example.com/default",
        "title": "Default headline",
        "summary": "Default summary",
        "source": "TestSource",
        "category": "stocks",
        "published_at": "2026-08-01T10:00:00+00:00",
        "collected_at": "2026-08-01T10:05:00+00:00",
        "duplicate_group_id": "group-1",
        "duplicate_group_size": 1,
        "companies_mentioned": [{"company": "Tesla", "ticker": "TSLA", "category": "stocks"}],
        "tickers_mentioned": [],
        "sectors": [{"sector": "Automotive", "source": "company", "via": ["Tesla"]}],
        "sentiment": {"score": 0.5, "label": "positive", "confidence": 0.4},
        "impact": {"score": 0.6, "level": "medium"},
    }
    base.update(overrides)
    return base


class TestSchemaInitialization(unittest.TestCase):
    """Tests that the table is created automatically and safely re-creatable."""

    def test_table_exists_after_construction(self):
        db = NewsDatabase(":memory:")
        # A query against the table must not raise if it exists.
        stats = db.get_stats()
        self.assertEqual(stats["total_articles"], 0)
        db.close()

    def test_reinitializing_schema_on_existing_db_is_safe(self):
        db = NewsDatabase(":memory:")
        db.save_articles([make_article()])
        db._initialize_schema()  # calling again must not wipe existing data
        self.assertEqual(db.get_stats()["total_articles"], 1)
        db.close()


class TestSaveArticles(unittest.TestCase):
    """Tests for save_articles(): insertion and URL-based idempotency."""

    def setUp(self):
        self.db = NewsDatabase(":memory:")

    def tearDown(self):
        self.db.close()

    def test_saves_new_article_and_returns_count_one(self):
        inserted = self.db.save_articles([make_article()])
        self.assertEqual(inserted, 1)
        self.assertEqual(self.db.get_stats()["total_articles"], 1)

    def test_saving_same_url_twice_is_idempotent(self):
        # Same URL, but a DIFFERENT article_id (simulating a fresh UUID
        # generated by a second collection run of the same real story).
        first_run = make_article(article_id="run1-id", url="https://example.com/tesla")
        second_run = make_article(article_id="run2-id", url="https://example.com/tesla")

        first_count = self.db.save_articles([first_run])
        second_count = self.db.save_articles([second_run])

        self.assertEqual(first_count, 1)
        self.assertEqual(second_count, 0)  # already known -> not re-inserted
        self.assertEqual(self.db.get_stats()["total_articles"], 1)  # still just 1 row

    def test_saves_multiple_distinct_articles(self):
        articles = [
            make_article(article_id="1", url="https://example.com/a"),
            make_article(article_id="2", url="https://example.com/b"),
        ]
        inserted = self.db.save_articles(articles)
        self.assertEqual(inserted, 2)

    def test_empty_list_returns_zero_and_does_not_raise(self):
        self.assertEqual(self.db.save_articles([]), 0)


class TestLoadArticles(unittest.TestCase):
    """Tests for load_all_articles() and the JSON round-trip of nested fields."""

    def setUp(self):
        self.db = NewsDatabase(":memory:")

    def tearDown(self):
        self.db.close()

    def test_loaded_article_matches_original_scalar_fields(self):
        original = make_article(title="Tesla shares surge", source="Reuters")
        self.db.save_articles([original])
        loaded = self.db.load_all_articles()[0]
        self.assertEqual(loaded["title"], "Tesla shares surge")
        self.assertEqual(loaded["source"], "Reuters")

    def test_nested_json_fields_round_trip_correctly(self):
        original = make_article()
        self.db.save_articles([original])
        loaded = self.db.load_all_articles()[0]

        self.assertEqual(loaded["companies_mentioned"], original["companies_mentioned"])
        self.assertEqual(loaded["sectors"], original["sectors"])
        self.assertEqual(loaded["sentiment"], original["sentiment"])
        self.assertEqual(loaded["impact"], original["impact"])

    def test_load_all_articles_returns_everything_stored(self):
        articles = [
            make_article(article_id="1", url="https://example.com/a"),
            make_article(article_id="2", url="https://example.com/b"),
            make_article(article_id="3", url="https://example.com/c"),
        ]
        self.db.save_articles(articles)
        loaded = self.db.load_all_articles()
        self.assertEqual(len(loaded), 3)

    def test_load_all_articles_on_empty_db_returns_empty_list(self):
        self.assertEqual(self.db.load_all_articles(), [])


class TestLoadArticlesSince(unittest.TestCase):
    """Tests for load_articles_since(): date-filtered retrieval."""

    def setUp(self):
        self.db = NewsDatabase(":memory:")
        self.db.save_articles([
            make_article(article_id="old", url="https://example.com/old",
                         collected_at="2026-07-01T00:00:00+00:00"),
            make_article(article_id="new", url="https://example.com/new",
                         collected_at="2026-08-01T00:00:00+00:00"),
        ])

    def tearDown(self):
        self.db.close()

    def test_filters_out_articles_before_cutoff(self):
        recent = self.db.load_articles_since("2026-07-15T00:00:00+00:00")
        ids = {a["article_id"] for a in recent}
        self.assertEqual(ids, {"new"})

    def test_cutoff_in_the_past_returns_everything(self):
        all_articles = self.db.load_articles_since("2000-01-01T00:00:00+00:00")
        self.assertEqual(len(all_articles), 2)


class TestArchiveOldArticles(unittest.TestCase):
    """Tests for archive_old_articles()."""

    def setUp(self):
        self.db = NewsDatabase(":memory:")
        old_date = (datetime.now(timezone.utc) - timedelta(days=100)).isoformat()
        recent_date = (datetime.now(timezone.utc) - timedelta(days=1)).isoformat()
        self.db.save_articles([
            make_article(article_id="old", url="https://example.com/old", collected_at=old_date),
            make_article(article_id="recent", url="https://example.com/recent", collected_at=recent_date),
        ])

    def tearDown(self):
        self.db.close()

    def test_removes_only_articles_older_than_cutoff(self):
        removed = self.db.archive_old_articles(older_than_days=30)
        self.assertEqual(removed, 1)
        remaining = self.db.load_all_articles()
        self.assertEqual(len(remaining), 1)
        self.assertEqual(remaining[0]["article_id"], "recent")

    def test_no_articles_older_than_cutoff_returns_zero(self):
        removed = self.db.archive_old_articles(older_than_days=365)
        self.assertEqual(removed, 0)
        self.assertEqual(len(self.db.load_all_articles()), 2)

    def test_archived_articles_are_saved_to_file_before_deletion(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            archive_path = os.path.join(tmp_dir, "archive.json")
            self.db.archive_old_articles(older_than_days=30, archive_path=archive_path)

            self.assertTrue(os.path.exists(archive_path))
            with open(archive_path, encoding="utf-8") as f:
                archived = json.load(f)
            self.assertEqual(len(archived), 1)
            self.assertEqual(archived[0]["article_id"], "old")

    def test_repeated_archival_appends_to_existing_file_not_overwrite(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            archive_path = os.path.join(tmp_dir, "archive.json")
            self.db.archive_old_articles(older_than_days=30, archive_path=archive_path)

            # Add and archive a second old article in a later "run".
            even_older = (datetime.now(timezone.utc) - timedelta(days=200)).isoformat()
            self.db.save_articles([make_article(article_id="older2", url="https://example.com/older2", collected_at=even_older)])
            self.db.archive_old_articles(older_than_days=30, archive_path=archive_path)

            with open(archive_path, encoding="utf-8") as f:
                archived = json.load(f)
            self.assertEqual(len(archived), 2)  # both archived batches preserved, not overwritten

    def test_corrupted_archive_file_does_not_block_archival(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            archive_path = os.path.join(tmp_dir, "archive.json")
            with open(archive_path, "w", encoding="utf-8") as f:
                f.write("{not valid json")

            removed = self.db.archive_old_articles(older_than_days=30, archive_path=archive_path)
            self.assertEqual(removed, 1)  # still archives successfully, starting a fresh file

    def test_no_archive_path_still_removes_from_live_table(self):
        removed = self.db.archive_old_articles(older_than_days=30, archive_path=None)
        self.assertEqual(removed, 1)
        self.assertEqual(len(self.db.load_all_articles()), 1)


class TestGetStats(unittest.TestCase):
    """Tests for get_stats()."""

    def setUp(self):
        self.db = NewsDatabase(":memory:")

    def tearDown(self):
        self.db.close()

    def test_stats_reflect_distinct_source_count(self):
        self.db.save_articles([
            make_article(article_id="1", url="https://example.com/a", source="Reuters"),
            make_article(article_id="2", url="https://example.com/b", source="Reuters"),
            make_article(article_id="3", url="https://example.com/c", source="CNBC"),
        ])
        stats = self.db.get_stats()
        self.assertEqual(stats["total_articles"], 3)
        self.assertEqual(stats["distinct_sources"], 2)

    def test_stats_on_empty_db(self):
        stats = self.db.get_stats()
        self.assertEqual(stats["total_articles"], 0)
        self.assertEqual(stats["distinct_sources"], 0)
        self.assertIsNone(stats["earliest_collected_at"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
