"""
Builds a comprehensive system dashboard covering every phase of the
pipeline — not just the legacy recommendation/portfolio view that
run_daily.py's DashboardGenerator produces today.

WHY THIS EXISTS AS A SEPARATE SCRIPT
-----------------------------------------
docs/index.html is generated by DashboardGenerator, fed exclusively by
legacy pipeline objects (recommendations, sector_scores, portfolio
history). None of Phases 3–10 — entity resolution, events, fusion,
market impact, research observations, features, models, or signals —
reach it. This script queries all of it: the legacy tables AND every
phase's tables, tolerating any that are missing or empty (an older
export, or a phase not yet run) rather than crashing.

THIS IS A STANDALONE, MANUALLY-TRIGGERED REPLACEMENT
----------------------------------------------------------
It writes to the same path (docs/index.html) but runs as its own
workflow, not wired into the daily pipeline. That is deliberate: the
person asked for this "at least temporarily", and the existing
DashboardGenerator would silently overwrite it on the next automatic
run otherwise. Making that permanent — replacing the daily pipeline's
own report step — is a separate decision.

EVERY SECTION DEGRADES INDEPENDENTLY
-----------------------------------------
Each phase's section is wrapped so a missing table or empty result
renders an honest "no data yet" card instead of taking down the whole
page. A dashboard that goes blank because one late phase has no rows
yet would be worse than one that plainly says so section by section.

NO INVENTED NUMBERS
------------------------
Every figure comes from a query against real tables. Where a metric
cannot be computed (e.g. no baseline, no signals yet), the card says
so rather than showing a zero that could be mistaken for a real
measurement.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DB = os.path.join(REPO_ROOT, "data", "marketlens.db")
DEFAULT_PAGE = os.path.join(REPO_ROOT, "docs", "index.html")


def table_exists(conn: sqlite3.Connection, name: str) -> bool:
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone() is not None


def scalar(conn: sqlite3.Connection, sql: str, params: tuple = (), default=None):
    try:
        row = conn.execute(sql, params).fetchone()
        return row[0] if row and row[0] is not None else default
    except sqlite3.OperationalError:
        return default


def rows(conn: sqlite3.Connection, sql: str, params: tuple = ()) -> List[tuple]:
    try:
        return conn.execute(sql, params).fetchall()
    except sqlite3.OperationalError:
        return []


def human_mb(byte_count: float) -> str:
    return f"{byte_count / (1024 * 1024):.1f} MB"


def esc(value: Any) -> str:
    return html.escape(str(value)) if value is not None else ""


def fmt_num(value: Optional[float], digits: int = 0) -> str:
    if value is None:
        return "—"
    return f"{value:,.{digits}f}"


def fmt_pct(value: Optional[float], digits: int = 1) -> str:
    if value is None:
        return "—"
    return f"{value * 100:.{digits}f}%"


def fmt_signed_pct(value: Optional[float], digits: int = 2) -> str:
    if value is None:
        return "—"
    sign = "+" if value >= 0 else ""
    return f"{sign}{value * 100:.{digits}f}%"


# ============================================================
# Per-phase data collection — each function is self-contained and
# tolerant of missing tables.
# ============================================================

def collect_pipeline_flow(conn: sqlite3.Connection) -> List[Dict]:
    """Row counts for the signature flow strip, in pipeline order."""
    stages = [
        ("Ingestie", "articles", "articole"),
        ("Entitati", "article_entities", "legaturi"),
        ("Evenimente", "events", "rapoarte"),
        ("Fuziune", "canonical_events", "evenimente"),
        ("Impact", "event_studies", "studii"),
        ("Cercetare", "research_observations", "observatii"),
        ("Caracteristici", "research_features", "valori"),
        ("Modele", "trained_models", "modele"),
        ("Semnale", "signals", "semnale"),
    ]
    flow = []
    for label, table, unit in stages:
        count = scalar(conn, f"SELECT COUNT(*) FROM {table}") if table_exists(conn, table) else None
        flow.append({"label": label, "count": count, "unit": unit})
    return flow


def collect_health(conn: sqlite3.Connection, db_path: str) -> Dict:
    size = os.path.getsize(db_path) if os.path.exists(db_path) else 0
    total_articles = scalar(conn, "SELECT COUNT(*) FROM articles", default=0) if table_exists(conn, "articles") else 0
    linked_articles = scalar(
        conn, "SELECT COUNT(DISTINCT article_id) FROM article_entities", default=0
    ) if table_exists(conn, "article_entities") else 0
    sources = scalar(conn, "SELECT COUNT(DISTINCT source) FROM articles WHERE source IS NOT NULL", default=0) \
        if table_exists(conn, "articles") else 0
    latest_article = scalar(conn, "SELECT MAX(published_at) FROM articles") if table_exists(conn, "articles") else None
    companies = scalar(conn, "SELECT COUNT(*) FROM companies", default=0) if table_exists(conn, "companies") else 0
    instruments = scalar(conn, "SELECT COUNT(*) FROM instruments", default=0) if table_exists(conn, "instruments") else 0
    return {
        "size_mb": human_mb(size), "total_articles": total_articles,
        "linked_articles": linked_articles,
        "entity_coverage": (linked_articles / total_articles) if total_articles else None,
        "sources": sources, "latest_article": latest_article,
        "companies": companies, "instruments": instruments,
    }


def collect_events(conn: sqlite3.Connection) -> Dict:
    if not table_exists(conn, "canonical_events"):
        return {"available": False}
    total = scalar(conn, "SELECT COUNT(*) FROM canonical_events", default=0)
    corroboration = rows(conn, """
        SELECT corroboration_state, COUNT(*) FROM canonical_events
        GROUP BY corroboration_state ORDER BY 2 DESC""")
    by_type = rows(conn, """
        SELECT event_type, COUNT(*) FROM canonical_events
        GROUP BY event_type ORDER BY 2 DESC LIMIT 8""")
    top_instruments = rows(conn, """
        SELECT cep.entity_id, COUNT(*) c FROM canonical_event_participants cep
        WHERE cep.role='primary' GROUP BY cep.entity_id ORDER BY c DESC LIMIT 8
    """) if table_exists(conn, "canonical_event_participants") else []
    return {"available": True, "total": total, "corroboration": corroboration,
            "by_type": by_type, "top_instruments": top_instruments}


def collect_impact(conn: sqlite3.Connection) -> Dict:
    if not table_exists(conn, "event_studies"):
        return {"available": False}
    total = scalar(conn, "SELECT COUNT(*) FROM event_studies", default=0)
    quality = rows(conn, "SELECT quality_level, COUNT(*) FROM event_studies GROUP BY quality_level ORDER BY 2 DESC")
    by_window = rows(conn, """
        SELECT window_name, COUNT(*), AVG(abnormal_return) FROM event_study_returns
        WHERE abnormal_return IS NOT NULL GROUP BY window_name ORDER BY window_name
    """) if table_exists(conn, "event_study_returns") else []
    return {"available": True, "total": total, "quality": quality, "by_window": by_window}


def collect_research(conn: sqlite3.Connection) -> Dict:
    if not table_exists(conn, "research_observations"):
        return {"available": False}
    total = scalar(conn, "SELECT COUNT(*) FROM research_observations", default=0)
    quality = rows(conn, "SELECT quality_level, COUNT(*) FROM research_observations GROUP BY quality_level ORDER BY 2 DESC")
    feature_coverage = rows(conn, """
        SELECT qualified_name, COUNT(DISTINCT observation_id) FROM research_features
        WHERE source='phase8_feature_engine' AND value_json != 'null'
        GROUP BY qualified_name ORDER BY 2 DESC
    """) if table_exists(conn, "research_features") else []
    total_features_attempted = scalar(conn, """
        SELECT COUNT(DISTINCT qualified_name) FROM research_features WHERE source='phase8_feature_engine'
    """, default=0) if table_exists(conn, "research_features") else 0
    return {"available": True, "total": total, "quality": quality,
            "feature_coverage": feature_coverage, "feature_count": total_features_attempted}


def collect_models(conn: sqlite3.Connection) -> Dict:
    if not table_exists(conn, "trained_models"):
        return {"available": False}
    models = rows(conn, """
        SELECT m.model_qualified_id, m.label_name, m.train_sample_size, m.train_cluster_count,
               e.small_sample, e.beats_all_baselines, e.metrics_json
        FROM trained_models m LEFT JOIN model_evaluations e ON e.trained_model_id = m.trained_model_id
        ORDER BY m.trained_at DESC LIMIT 10
    """) if table_exists(conn, "trained_models") else []
    predictions = scalar(conn, "SELECT COUNT(*) FROM predictions", default=0) if table_exists(conn, "predictions") else 0
    return {"available": True, "models": models, "predictions": predictions}


def collect_signals(conn: sqlite3.Connection) -> Dict:
    if not table_exists(conn, "signals"):
        return {"available": False}
    total = scalar(conn, "SELECT COUNT(*) FROM signals", default=0)
    by_status = rows(conn, "SELECT status, COUNT(*) FROM signals GROUP BY status ORDER BY 2 DESC")
    by_direction = rows(conn, """
        SELECT direction, COUNT(*) FROM signals WHERE status='active' GROUP BY direction ORDER BY 2 DESC
    """)
    suppression = rows(conn, """
        SELECT reason, COUNT(*) FROM signal_suppressions GROUP BY reason ORDER BY 2 DESC
    """) if table_exists(conn, "signal_suppressions") else []
    recent = rows(conn, """
        SELECT instrument_id, direction, status, strength, confidence,
               expected_return, source_information_cutoff
        FROM signals ORDER BY source_information_cutoff DESC LIMIT 12
    """)
    evaluations = rows(conn, """
        SELECT cohort_kind, cohort_value, horizon, sample_size, hit_rate,
               baseline_hit_rate, beats_baseline, small_sample
        FROM signal_evaluations WHERE cohort_kind='overall' ORDER BY horizon
    """) if table_exists(conn, "signal_evaluations") else []
    return {"available": True, "total": total, "by_status": by_status,
            "by_direction": by_direction, "suppression": suppression,
            "recent": recent, "evaluations": evaluations}


def collect_legacy_portfolio(conn: sqlite3.Connection) -> Dict:
    if not table_exists(conn, "recommendations"):
        return {"available": False}
    total_recs = scalar(conn, "SELECT COUNT(*) FROM recommendations", default=0)
    by_rec = rows(conn, "SELECT recommendation, COUNT(*) FROM recommendations GROUP BY recommendation ORDER BY 2 DESC")
    checked = scalar(conn, "SELECT COUNT(*) FROM recommendations WHERE was_correct IS NOT NULL", default=0)
    correct = scalar(conn, "SELECT COUNT(*) FROM recommendations WHERE was_correct = 1", default=0)
    latest_snapshot = rows(conn, """
        SELECT recorded_at, total_invested, total_final_value, total_return_pct, trades_simulated
        FROM portfolio_snapshots ORDER BY recorded_at DESC LIMIT 1
    """) if table_exists(conn, "portfolio_snapshots") else []
    return {"available": True, "total_recs": total_recs, "by_rec": by_rec,
            "checked": checked, "correct": correct,
            "accuracy": (correct / checked) if checked else None,
            "latest_snapshot": latest_snapshot[0] if latest_snapshot else None}


# ============================================================
# Rendering
# ============================================================

STATUS_COLOR = {"active": "up", "suppressed": "warn", "expired": "muted",
                "superseded": "muted", "rejected": "down"}


def render_flow_strip(flow: List[Dict]) -> str:
    nodes = []
    for i, stage in enumerate(flow):
        count = stage["count"]
        display = fmt_num(count) if count is not None else "n/a"
        empty = " flow-node--empty" if not count else ""
        nodes.append(f"""<div class="flow-node{empty}">
<div class="flow-count">{display}</div>
<div class="flow-label">{esc(stage['label'])}</div>
<div class="flow-unit">{esc(stage['unit'])}</div>
</div>""")
        if i < len(flow) - 1:
            nodes.append('<div class="flow-line"></div>')
    return "\n".join(nodes)


def render_bar_rows(pairs: List[tuple], value_fmt=fmt_num) -> str:
    if not pairs:
        return '<div class="empty-note">Fara date.</div>'
    max_value = max((p[1] or 0) for p in pairs) or 1
    out = []
    for label, value in pairs:
        pct = 100 * (value or 0) / max_value
        out.append(f"""<div class="bar-row">
<div class="bar-label">{esc(label)}</div>
<div class="bar-track"><div class="bar-fill" style="width:{pct:.1f}%"></div></div>
<div class="bar-value">{value_fmt(value)}</div>
</div>""")
    return "\n".join(out)


def render_dashboard(conn: sqlite3.Connection, db_path: str) -> str:
    flow = collect_pipeline_flow(conn)
    health = collect_health(conn, db_path)
    events = collect_events(conn)
    impact = collect_impact(conn)
    research = collect_research(conn)
    models = collect_models(conn)
    signals = collect_signals(conn)
    legacy = collect_legacy_portfolio(conn)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # --- Events section ---
    events_html = '<div class="empty-note">Faza 5 nu a rulat inca.</div>'
    if events.get("available"):
        events_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(events['total'])}</div><div class="stat-label">evenimente canonice</div></div>
</div>
<div class="split">
  <div>
    <div class="subhead">Stare de corroborare</div>
    {render_bar_rows(events['corroboration'])}
  </div>
  <div>
    <div class="subhead">Pe tip de eveniment</div>
    {render_bar_rows(events['by_type'])}
  </div>
</div>"""

    # --- Impact section ---
    impact_html = '<div class="empty-note">Faza 6 nu a rulat inca.</div>'
    if impact.get("available"):
        window_rows = "".join(
            f"<tr><td>{esc(w)}</td><td class='num'>{n}</td><td class='num signed'>{fmt_signed_pct(avg)}</td></tr>"
            for w, n, avg in impact["by_window"])
        impact_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(impact['total'])}</div><div class="stat-label">studii de impact</div></div>
</div>
<div class="split">
  <div>
    <div class="subhead">Calitate</div>
    {render_bar_rows(impact['quality'])}
  </div>
  <div>
    <div class="subhead">Randament anormal mediu pe fereastra</div>
    <table class="mini"><thead><tr><th>Fereastra</th><th class="num">N</th><th class="num">Randament</th></tr></thead>
    <tbody>{window_rows or '<tr><td colspan=3>Fara date</td></tr>'}</tbody></table>
  </div>
</div>"""

    # --- Research section ---
    research_html = '<div class="empty-note">Faza 7 nu a rulat inca.</div>'
    if research.get("available"):
        total_obs = research["total"] or 0
        feat_rows = "".join(
            f"""<div class="bar-row"><div class="bar-label mono">{esc(name)}</div>
<div class="bar-track"><div class="bar-fill" style="width:{100*n/total_obs if total_obs else 0:.1f}%"></div></div>
<div class="bar-value">{fmt_pct(n/total_obs if total_obs else None)}</div></div>"""
            for name, n in research["feature_coverage"][:12])
        research_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(research['total'])}</div><div class="stat-label">observatii de cercetare</div></div>
  <div class="stat"><div class="stat-value">{fmt_num(research['feature_count'])}</div><div class="stat-label">caracteristici in registru</div></div>
</div>
<div class="split">
  <div>
    <div class="subhead">Calitate observatii</div>
    {render_bar_rows(research['quality'])}
  </div>
  <div>
    <div class="subhead">Acoperire caracteristici (top 12)</div>
    {feat_rows or '<div class="empty-note">Faza 8 nu a rulat inca.</div>'}
  </div>
</div>"""

    # --- Models section ---
    models_html = '<div class="empty-note">Faza 9 nu a rulat inca.</div>'
    if models.get("available"):
        model_rows = []
        for qid, label, n, clusters, small, beats, metrics_json in models["models"]:
            try:
                metrics = json.loads(metrics_json) if metrics_json else {}
            except (ValueError, TypeError):
                metrics = {}
            flag = '<span class="badge warn">esantion mic</span>' if small else ""
            verdict = ('<span class="badge up">bate baseline</span>' if beats
                       else '<span class="badge down">nu bate</span>' if beats is not None else "—")
            model_rows.append(f"""<tr>
<td class="mono small">{esc(qid)}</td><td>{esc(label)}</td><td class="num">{fmt_num(n)}</td>
<td class="num">{fmt_num(clusters)}</td><td class="num">{fmt_num(metrics.get('mae'), 4)}</td>
<td>{verdict} {flag}</td></tr>""")
        models_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(len(models['models']))}</div><div class="stat-label">modele antrenate</div></div>
  <div class="stat"><div class="stat-value">{fmt_num(models['predictions'])}</div><div class="stat-label">predictii stocate</div></div>
</div>
<table class="mini">
<thead><tr><th>Model</th><th>Eticheta</th><th class="num">N antrenare</th><th class="num">Clustere</th><th class="num">MAE</th><th>Verdict</th></tr></thead>
<tbody>{"".join(model_rows) or '<tr><td colspan=6>Fara modele</td></tr>'}</tbody>
</table>"""

    # --- Signals section ---
    signals_html = '<div class="empty-note">Faza 10 nu a rulat inca.</div>'
    if signals.get("available"):
        recent_rows = []
        for instrument, direction, status, strength, confidence, expected, cutoff in signals["recent"]:
            dir_class = "up" if direction == "long" else "down" if direction == "short" else "muted"
            status_class = STATUS_COLOR.get(status, "muted")
            recent_rows.append(f"""<tr>
<td class="mono">{esc(instrument)}</td>
<td><span class="pill {dir_class}">{esc(direction)}</span></td>
<td><span class="badge {status_class}">{esc(status)}</span></td>
<td class="num">{fmt_num(strength, 2)}</td>
<td class="num">{fmt_num(confidence, 2)}</td>
<td class="num signed">{fmt_signed_pct(expected)}</td>
<td class="mono small">{esc((cutoff or '')[:16])}</td>
</tr>""")

        eval_rows = []
        for kind, value, horizon, n, hit, baseline, beats, small in signals["evaluations"]:
            verdict = ('<span class="badge up">da</span>' if beats
                       else '<span class="badge down">nu</span>' if beats is not None else "—")
            flag = ' <span class="badge warn">mic</span>' if small else ""
            eval_rows.append(f"""<tr><td>{esc(horizon)}</td><td class="num">{n}{flag}</td>
<td class="num">{fmt_pct(hit)}</td><td class="num">{fmt_pct(baseline)}</td><td>{verdict}</td></tr>""")

        signals_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(signals['total'])}</div><div class="stat-label">semnale totale</div></div>
</div>
<div class="split">
  <div>
    <div class="subhead">Dupa stare</div>
    {render_bar_rows(signals['by_status'])}
  </div>
  <div>
    <div class="subhead">Motive de suprimare</div>
    {render_bar_rows(signals['suppression'])}
  </div>
</div>
<div class="subhead" style="margin-top:22px">Evaluare (rata de succes vs. baseline)</div>
<table class="mini">
<thead><tr><th>Orizont</th><th class="num">N</th><th class="num">Rata succes</th><th class="num">Baseline</th><th>Bate</th></tr></thead>
<tbody>{"".join(eval_rows) or '<tr><td colspan=5>Nicio evaluare inca</td></tr>'}</tbody>
</table>
<div class="subhead" style="margin-top:22px">Semnale recente</div>
<table class="mini">
<thead><tr><th>Instrument</th><th>Directie</th><th>Stare</th><th class="num">Forta</th><th class="num">Incredere</th><th class="num">R. asteptat</th><th>Cutoff</th></tr></thead>
<tbody>{"".join(recent_rows) or '<tr><td colspan=7>Niciun semnal</td></tr>'}</tbody>
</table>"""

    # --- Legacy portfolio section ---
    legacy_html = '<div class="empty-note">Fara date legacy.</div>'
    if legacy.get("available"):
        snap = legacy.get("latest_snapshot")
        snap_html = ""
        if snap:
            recorded_at, invested, final_value, return_pct, trades = snap
            snap_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(invested, 0)}</div><div class="stat-label">investit (simulat)</div></div>
  <div class="stat"><div class="stat-value signed">{fmt_signed_pct(return_pct / 100 if return_pct else None)}</div><div class="stat-label">randament simulat</div></div>
  <div class="stat"><div class="stat-value">{fmt_num(trades, 0)}</div><div class="stat-label">tranzactii simulate</div></div>
</div>"""
        legacy_html = f"""
<div class="stat-row">
  <div class="stat"><div class="stat-value">{fmt_num(legacy['total_recs'])}</div><div class="stat-label">recomandari emise</div></div>
  <div class="stat"><div class="stat-value">{fmt_pct(legacy['accuracy'])}</div><div class="stat-label">acuratete verificata ({fmt_num(legacy['checked'])} verificate)</div></div>
</div>
{snap_html}
<div class="subhead">Dupa tip</div>
{render_bar_rows(legacy['by_rec'])}"""

    page = f"""<!DOCTYPE html>
<html lang="ro">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MarketLens — Panou de Control</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root {{
  --bg:#0B0E14; --surface:#131722; --surface-2:#171c28; --border:#232838;
  --text:#E6E9F0; --text-dim:#7C8494; --text-faint:#4B5266;
  --up:#17C787; --down:#F0524D; --accent:#4C8DFF; --warn:#E8A33D;
}}
* {{ box-sizing:border-box; }}
html,body {{ margin:0; background:var(--bg); color:var(--text); font-family:'Manrope',system-ui,sans-serif; }}
.mono {{ font-family:'JetBrains Mono',ui-monospace,monospace; }}
a {{ color:var(--accent); }}

.topbar {{ position:sticky; top:0; z-index:20; background:rgba(11,14,20,.92); backdrop-filter:blur(8px);
  border-bottom:1px solid var(--border); padding:14px 24px; display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:10px; }}
.brand {{ font-weight:800; font-size:16px; letter-spacing:.3px; }}
.brand .dot {{ color:var(--up); }}
.meta {{ font-size:12px; color:var(--text-dim); font-family:'JetBrains Mono',monospace; }}

.wrap {{ max-width:1280px; margin:0 auto; padding:26px 20px 70px; }}

.flow {{ display:flex; align-items:stretch; overflow-x:auto; gap:0; margin:6px 0 34px;
  padding:20px 4px; border:1px solid var(--border); border-radius:10px; background:var(--surface); }}
.flow-node {{ flex:1; min-width:96px; text-align:center; padding:0 10px; }}
.flow-node--empty {{ opacity:.35; }}
.flow-count {{ font-family:'JetBrains Mono',monospace; font-weight:700; font-size:20px; color:var(--accent); }}
.flow-label {{ font-size:11px; text-transform:uppercase; letter-spacing:1px; color:var(--text); margin-top:4px; font-weight:600; }}
.flow-unit {{ font-size:10px; color:var(--text-faint); margin-top:1px; }}
.flow-line {{ width:22px; align-self:center; height:1px; background:var(--border); flex-shrink:0; margin-top:-14px; }}

.section {{ margin-bottom:30px; border:1px solid var(--border); border-radius:10px; background:var(--surface); padding:22px 24px; }}
.section h2 {{ font-size:15px; text-transform:uppercase; letter-spacing:1.2px; margin:0 0 18px; color:var(--text);
  display:flex; align-items:center; gap:10px; }}
.section h2 .n {{ font-family:'JetBrains Mono',monospace; color:var(--text-faint); font-size:12px; }}

.stat-row {{ display:flex; gap:34px; flex-wrap:wrap; margin-bottom:20px; }}
.stat-value {{ font-family:'JetBrains Mono',monospace; font-weight:700; font-size:26px; }}
.stat-value.signed {{ color:var(--up); }}
.stat-label {{ font-size:11px; color:var(--text-dim); margin-top:3px; text-transform:uppercase; letter-spacing:.6px; }}

.split {{ display:grid; grid-template-columns:1fr 1fr; gap:30px; }}
@media (max-width:760px) {{ .split {{ grid-template-columns:1fr; }} }}

.subhead {{ font-size:11px; text-transform:uppercase; letter-spacing:1px; color:var(--text-dim); margin-bottom:10px; font-weight:700; }}

.bar-row {{ display:grid; grid-template-columns:130px 1fr 60px; align-items:center; gap:10px; margin-bottom:7px; font-size:12px; }}
.bar-label {{ color:var(--text-dim); overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }}
.bar-track {{ height:6px; background:var(--surface-2); border-radius:3px; overflow:hidden; }}
.bar-fill {{ height:100%; background:var(--accent); border-radius:3px; }}
.bar-value {{ text-align:right; font-family:'JetBrains Mono',monospace; color:var(--text); }}

table.mini {{ width:100%; border-collapse:collapse; font-size:12.5px; }}
table.mini th {{ text-align:left; font-size:10px; text-transform:uppercase; letter-spacing:.8px; color:var(--text-faint);
  border-bottom:1px solid var(--border); padding:7px 8px; font-weight:600; }}
table.mini td {{ padding:8px 8px; border-bottom:1px solid var(--surface-2); }}
table.mini td.num {{ text-align:right; font-family:'JetBrains Mono',monospace; }}
table.mini td.signed {{ color:var(--up); }}
.small {{ font-size:11px; color:var(--text-dim); }}

.badge {{ display:inline-block; padding:2px 8px; border-radius:3px; font-size:10px; letter-spacing:.6px; text-transform:uppercase; font-weight:700; }}
.badge.up {{ background:rgba(23,199,135,.14); color:var(--up); }}
.badge.down {{ background:rgba(240,82,77,.14); color:var(--down); }}
.badge.warn {{ background:rgba(232,163,61,.14); color:var(--warn); }}
.badge.muted {{ background:rgba(124,132,148,.14); color:var(--text-dim); }}
.pill {{ font-weight:700; font-size:12px; }}
.pill.up {{ color:var(--up); }} .pill.down {{ color:var(--down); }} .pill.muted {{ color:var(--text-dim); }}

.empty-note {{ color:var(--text-faint); font-size:12.5px; font-style:italic; padding:10px 0; }}
.notice {{ border:1px solid var(--warn); background:rgba(232,163,61,.08); border-radius:8px;
  padding:14px 16px; font-size:12.5px; line-height:1.6; color:#d9c19a; margin-bottom:26px; }}
.foot {{ text-align:center; color:var(--text-faint); font-size:11px; margin-top:40px; font-family:'JetBrains Mono',monospace; }}
</style>
</head>
<body>
<div class="topbar">
  <div class="brand">MarketLens <span class="dot">●</span> Panou de Control</div>
  <div class="meta">generat {generated} · {health['size_mb']}</div>
</div>
<div class="wrap">

<div class="notice">
Acest panou acopera toate fazele pipeline-ului, inclusiv Fazele 3–10 (entitati, evenimente, fuziune,
impact de piata, dataset de cercetare, caracteristici, modele, semnale), pe langa recomandarile
si portofoliul simulat din pipeline-ul original. Sectiunile fara date arata explicit acest lucru,
in loc sa fie omise sau completate cu valori inventate.
</div>

<div class="flow">
{render_flow_strip(flow)}
</div>

<div class="section">
  <h2>Sanatatea datelor</h2>
  <div class="stat-row">
    <div class="stat"><div class="stat-value">{fmt_num(health['total_articles'])}</div><div class="stat-label">articole totale</div></div>
    <div class="stat"><div class="stat-value">{fmt_pct(health['entity_coverage'])}</div><div class="stat-label">acoperire entitati</div></div>
    <div class="stat"><div class="stat-value">{fmt_num(health['sources'])}</div><div class="stat-label">surse active</div></div>
    <div class="stat"><div class="stat-value">{fmt_num(health['companies'])}</div><div class="stat-label">companii in registru</div></div>
    <div class="stat"><div class="stat-value">{fmt_num(health['instruments'])}</div><div class="stat-label">instrumente</div></div>
  </div>
  <div class="small">Cel mai recent articol: {esc((health['latest_article'] or 'necunoscut')[:19])}</div>
</div>

<div class="section">
  <h2>Evenimente si Fuziune <span class="n">Faze 4–5</span></h2>
  {events_html}
</div>

<div class="section">
  <h2>Impact de Piata <span class="n">Faza 6</span></h2>
  {impact_html}
</div>

<div class="section">
  <h2>Dataset de Cercetare si Caracteristici <span class="n">Faze 7–8</span></h2>
  {research_html}
</div>

<div class="section">
  <h2>Modele <span class="n">Faza 9</span></h2>
  {models_html}
</div>

<div class="section">
  <h2>Semnale <span class="n">Faza 10</span></h2>
  {signals_html}
</div>

<div class="section">
  <h2>Recomandari si Portofoliu (legacy)</h2>
  {legacy_html}
</div>

<div class="foot">MarketLens · panou reconstruit manual · nu contine sfaturi de investitii</div>
</div>
</body>
</html>"""
    return page


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default=DEFAULT_DB)
    parser.add_argument("--out", default=DEFAULT_PAGE)
    args = parser.parse_args()

    if not os.path.exists(args.db):
        print(f"EROARE: baza nu exista: {args.db}")
        return 1

    conn = sqlite3.connect(args.db)
    page = render_dashboard(conn, args.db)
    conn.close()

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(page)

    print(f"Dashboard generat: {args.out} ({len(page):,} caractere)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
