"""
sector_registry.py
---------------------
Sector classification data for MarketLens.

Two complementary sources of sector information:

1. COMPANY_SECTOR_MAP — maps each company already known to Company
   Detector (by canonical_name) to its primary economic sector. This is
   the HIGH-CONFIDENCE path: if an article already mentions a known
   company, we already know precisely which one, so its sector follows
   directly — no guessing involved.

2. SECTOR_KEYWORDS — a FALLBACK path for articles that discuss a sector
   generically without naming any specific known company (e.g. "oil
   prices surge amid supply concerns" mentions no company but is
   clearly an Energy story). Matched with lower confidence than the
   company-based path, and only ever used when it doesn't.

Kept as a separate file so growing either list never requires touching
sector_detector.py's logic — the same "add a line, not code" principle
used by company_registry.py and ticker_registry.py.

CHANGE LOG (v1.3): expanded alongside company_registry.py's v1.3
expansion (123 -> 389 companies). Every new company added there has a
matching entry here. Two brand-new sectors introduced: "Real Estate"
and "Materials & Mining" (previously only reachable via BVB's "One
United Properties" tagged as Real Estate on its own).
"""

from typing import Dict, List

# Canonical company name (must match company_registry.py's
# canonical_name exactly) -> primary economic sector.
COMPANY_SECTOR_MAP: Dict[str, str] = {
    # --- BVB ---
    "Banca Transilvania": "Financial Services",
    "Hidroelectrica": "Energy",
    "OMV Petrom": "Energy",
    "Nuclearelectrica": "Energy",
    "Romgaz": "Energy",
    "Transgaz": "Utilities",
    "Electrica": "Utilities",
    "BRD - Groupe Societe Generale": "Financial Services",
    "Digi Communications": "Telecommunications",
    "Fondul Proprietatea": "Financial Services",
    "Purcari Wineries": "Consumer Goods",
    "MedLife": "Healthcare",
    "Sphera Franchise Group": "Consumer Goods",
    "TeraPlast": "Industrials",
    "One United Properties": "Real Estate",
    "Transelectrica": "Utilities",
    "Antibiotice": "Healthcare",
    "Aquila": "Industrials",
    "Bursa de Valori Bucuresti": "Financial Services",
    "Conpet": "Energy",
    "Alro": "Industrials",
    "Vrancart": "Industrials",
    "Bittnet Systems": "Technology",
    "Patria Bank": "Financial Services",
    "SIF Banat-Crisana": "Financial Services",
    "SIF Moldova": "Financial Services",
    "SIF Muntenia": "Financial Services",
    "SIF Oltenia": "Financial Services",
    "SIF Transilvania": "Financial Services",
    "Aerostar": "Industrials",
    "Romcarbon": "Industrials",
    "IAR SA": "Industrials",

    # --- International: Technology ---
    "Apple": "Technology",
    "Microsoft": "Technology",
    "Alphabet": "Technology",
    "Meta Platforms": "Technology",
    "Nvidia": "Technology",
    "Intel": "Technology",
    "AMD": "Technology",
    "Oracle": "Technology",
    "Salesforce": "Technology",
    "Adobe": "Technology",
    "IBM": "Technology",
    "Qualcomm": "Technology",
    "Cisco": "Technology",
    "Uber Technologies": "Technology",
    "ServiceNow": "Technology",
    "Palantir Technologies": "Technology",
    "Shopify": "Technology",
    "Zoom Communications": "Technology",
    "Snowflake": "Technology",
    "SAP": "Technology",
    "Intuit": "Technology",
    "Autodesk": "Technology",
    "Synopsys": "Technology",
    "Cadence Design Systems": "Technology",
    "Palo Alto Networks": "Technology",
    "CrowdStrike": "Technology",
    "Fortinet": "Technology",
    "Datadog": "Technology",
    "MongoDB": "Technology",
    "Atlassian": "Technology",
    "HubSpot": "Technology",
    "DocuSign": "Technology",
    "Dropbox": "Technology",
    "Twilio": "Technology",
    "Okta": "Technology",
    "Akamai Technologies": "Technology",
    "Dell Technologies": "Technology",
    "HP Inc": "Technology",
    "Hewlett Packard Enterprise": "Technology",
    "Western Digital": "Technology",
    "Seagate Technology": "Technology",
    "Corning": "Technology",
    "Motorola Solutions": "Technology",
    "Garmin": "Technology",
    "Logitech": "Technology",
    "NetApp": "Technology",
    "Juniper Networks": "Technology",
    "Arista Networks": "Technology",
    "F5 Inc": "Technology",
    "Trimble": "Technology",
    "Workday": "Technology",
    "ANSYS": "Technology",
    "PTC Inc": "Technology",
    "Check Point Software Technologies": "Technology",
    "Zscaler": "Technology",

    # --- International: Semiconductors ---
    "Broadcom": "Semiconductors",
    "Texas Instruments": "Semiconductors",
    "Micron Technology": "Semiconductors",
    "ASML Holding": "Semiconductors",
    "Applied Materials": "Semiconductors",
    "Lam Research": "Semiconductors",
    "KLA Corporation": "Semiconductors",
    "Analog Devices": "Semiconductors",
    "NXP Semiconductors": "Semiconductors",
    "Marvell Technology": "Semiconductors",
    "ON Semiconductor": "Semiconductors",
    "Skyworks Solutions": "Semiconductors",
    "Qorvo": "Semiconductors",
    "Microchip Technology": "Semiconductors",
    "Teradyne": "Semiconductors",
    "Entegris": "Semiconductors",
    "MKS Instruments": "Semiconductors",
    "GlobalFoundries": "Semiconductors",

    # --- International: Automotive ---
    "Tesla": "Automotive",
    "Ford Motor Company": "Automotive",
    "General Motors": "Automotive",
    "Toyota": "Automotive",
    "Rivian Automotive": "Automotive",
    "Lucid Group": "Automotive",
    "Honda Motor": "Automotive",
    "Volkswagen": "Automotive",
    "BMW": "Automotive",
    "Mercedes-Benz Group": "Automotive",
    "Stellantis": "Automotive",
    "Ferrari": "Automotive",
    "Porsche": "Automotive",
    "Nio": "Automotive",
    "XPeng": "Automotive",
    "BYD Company": "Automotive",
    "Harley-Davidson": "Automotive",
    "Aptiv": "Automotive",
    "BorgWarner": "Automotive",

    # --- International: Healthcare ---
    "Johnson & Johnson": "Healthcare",
    "Pfizer": "Healthcare",
    "UnitedHealth Group": "Healthcare",
    "Moderna": "Healthcare",
    "Eli Lilly": "Healthcare",
    "Abbott Laboratories": "Healthcare",
    "Merck & Co": "Healthcare",
    "Bristol Myers Squibb": "Healthcare",
    "CVS Health": "Healthcare",
    "Amgen": "Healthcare",
    "Gilead Sciences": "Healthcare",
    "Biogen": "Healthcare",
    "Regeneron Pharmaceuticals": "Healthcare",
    "Vertex Pharmaceuticals": "Healthcare",
    "Zoetis": "Healthcare",
    "Stryker": "Healthcare",
    "Medtronic": "Healthcare",
    "Boston Scientific": "Healthcare",
    "Becton Dickinson": "Healthcare",
    "Danaher": "Healthcare",
    "Thermo Fisher Scientific": "Healthcare",
    "IQVIA": "Healthcare",
    "Illumina": "Healthcare",
    "Humana": "Healthcare",
    "Cigna": "Healthcare",
    "Elevance Health": "Healthcare",
    "Centene Corporation": "Healthcare",
    "HCA Healthcare": "Healthcare",
    "DaVita": "Healthcare",
    "Baxter International": "Healthcare",
    "Cardinal Health": "Healthcare",
    "McKesson": "Healthcare",
    "Cencora": "Healthcare",
    "GSK": "Healthcare",
    "AstraZeneca": "Healthcare",
    "Novartis": "Healthcare",
    "Roche": "Healthcare",
    "Sanofi": "Healthcare",
    "Novo Nordisk": "Healthcare",

    # --- International: Financial Services ---
    "JPMorgan Chase": "Financial Services",
    "Goldman Sachs": "Financial Services",
    "Bank of America": "Financial Services",
    "Wells Fargo": "Financial Services",
    "Visa": "Financial Services",
    "Mastercard": "Financial Services",
    "Morgan Stanley": "Financial Services",
    "Charles Schwab": "Financial Services",
    "American Express": "Financial Services",
    "BlackRock": "Financial Services",
    "PayPal": "Financial Services",
    "Citigroup": "Financial Services",
    "US Bancorp": "Financial Services",
    "PNC Financial Services": "Financial Services",
    "Truist Financial": "Financial Services",
    "Capital One Financial": "Financial Services",
    "Fifth Third Bancorp": "Financial Services",
    "State Street Corporation": "Financial Services",
    "Bank of New York Mellon": "Financial Services",
    "Ally Financial": "Financial Services",
    "Discover Financial Services": "Financial Services",
    "Synchrony Financial": "Financial Services",
    "Prudential Financial": "Financial Services",
    "MetLife": "Financial Services",
    "Aflac": "Financial Services",
    "Progressive Corporation": "Financial Services",
    "Allstate": "Financial Services",
    "Travelers Companies": "Financial Services",
    "Chubb Limited": "Financial Services",
    "Marsh McLennan": "Financial Services",
    "Aon": "Financial Services",
    "Arthur J Gallagher": "Financial Services",
    "Moody's Corporation": "Financial Services",
    "S&P Global": "Financial Services",
    "Intercontinental Exchange": "Financial Services",
    "Nasdaq Inc": "Financial Services",
    "CME Group": "Financial Services",
    "Ameriprise Financial": "Financial Services",
    "Raymond James Financial": "Financial Services",
    "T Rowe Price": "Financial Services",
    "Invesco": "Financial Services",
    "Berkshire Hathaway": "Financial Services",

    # --- International: Consumer Goods & Retail ---
    "Amazon": "Retail & E-commerce",
    "Walmart": "Retail & E-commerce",
    "Costco": "Retail & E-commerce",
    "Target": "Retail & E-commerce",
    "Home Depot": "Retail & E-commerce",
    "Lowe's": "Retail & E-commerce",
    "Kroger": "Retail & E-commerce",
    "TJX Companies": "Retail & E-commerce",
    "Ross Stores": "Retail & E-commerce",
    "Dollar General": "Retail & E-commerce",
    "Dollar Tree": "Retail & E-commerce",
    "Best Buy": "Retail & E-commerce",
    "AutoZone": "Retail & E-commerce",
    "O'Reilly Automotive": "Retail & E-commerce",
    "Procter & Gamble": "Consumer Goods",
    "Coca-Cola": "Consumer Goods",
    "PepsiCo": "Consumer Goods",
    "Nike": "Consumer Goods",
    "McDonald's": "Consumer Goods",
    "Starbucks": "Consumer Goods",
    "Colgate-Palmolive": "Consumer Goods",
    "Kimberly-Clark": "Consumer Goods",
    "Church & Dwight": "Consumer Goods",
    "Kraft Heinz": "Consumer Goods",
    "General Mills": "Consumer Goods",
    "Kellanova": "Consumer Goods",
    "Mondelez International": "Consumer Goods",
    "Hershey": "Consumer Goods",
    "Constellation Brands": "Consumer Goods",
    "Molson Coors": "Consumer Goods",
    "Monster Beverage": "Consumer Goods",
    "Estee Lauder": "Consumer Goods",
    "Clorox": "Consumer Goods",
    "Yum! Brands": "Consumer Goods",
    "Chipotle Mexican Grill": "Consumer Goods",
    "Darden Restaurants": "Consumer Goods",
    "Domino's Pizza": "Consumer Goods",

    # --- International: Energy ---
    "ExxonMobil": "Energy",
    "Chevron": "Energy",
    "Shell": "Energy",
    "ConocoPhillips": "Energy",
    "Occidental Petroleum": "Energy",
    "Marathon Petroleum": "Energy",
    "Phillips 66": "Energy",
    "Valero Energy": "Energy",
    "Williams Companies": "Energy",
    "Kinder Morgan": "Energy",
    "ONEOK": "Energy",
    "Baker Hughes": "Energy",
    "Halliburton": "Energy",
    "Schlumberger": "Energy",
    "EOG Resources": "Energy",
    "Devon Energy": "Energy",
    "Coterra Energy": "Energy",
    "Diamondback Energy": "Energy",
    "NextEra Energy": "Utilities",
    "Duke Energy": "Utilities",
    "Southern Company": "Utilities",
    "Dominion Energy": "Utilities",
    "American Electric Power": "Utilities",
    "Exelon": "Utilities",
    "Sempra": "Utilities",
    "PG&E Corporation": "Utilities",
    "Edison International": "Utilities",
    "Xcel Energy": "Utilities",
    "WEC Energy Group": "Utilities",
    "Entergy": "Utilities",
    "Public Service Enterprise Group": "Utilities",

    # --- International: Media & Entertainment ---
    "Netflix": "Media & Entertainment",
    "Walt Disney": "Media & Entertainment",
    "Warner Bros Discovery": "Media & Entertainment",
    "Comcast": "Media & Entertainment",
    "Spotify": "Media & Entertainment",
    "Paramount Global": "Media & Entertainment",
    "Fox Corporation": "Media & Entertainment",
    "News Corp": "Media & Entertainment",
    "Live Nation Entertainment": "Media & Entertainment",
    "Electronic Arts": "Media & Entertainment",
    "Take-Two Interactive": "Media & Entertainment",
    "Roku": "Media & Entertainment",

    # --- International: Industrials ---
    "Boeing": "Industrials",
    "Caterpillar": "Industrials",
    "General Electric": "Industrials",
    "Honeywell": "Industrials",
    "3M": "Industrials",
    "Lockheed Martin": "Industrials",
    "RTX Corporation": "Industrials",
    "Union Pacific Corporation": "Industrials",
    "Norfolk Southern": "Industrials",
    "CSX Corporation": "Industrials",
    "FedEx": "Industrials",
    "United Parcel Service": "Industrials",
    "Deere & Company": "Industrials",
    "Parker Hannifin": "Industrials",
    "Illinois Tool Works": "Industrials",
    "Emerson Electric": "Industrials",
    "Eaton Corporation": "Industrials",
    "Cummins": "Industrials",
    "PACCAR": "Industrials",
    "Northrop Grumman": "Industrials",
    "General Dynamics": "Industrials",
    "L3Harris Technologies": "Industrials",
    "TransDigm Group": "Industrials",
    "Waste Management": "Industrials",
    "Republic Services": "Industrials",
    "Xylem": "Industrials",

    # --- International: Airlines ---
    "Delta Air Lines": "Airlines & Aviation",
    "United Airlines": "Airlines & Aviation",
    "Southwest Airlines": "Airlines & Aviation",
    "American Airlines": "Airlines & Aviation",
    "Alaska Air Group": "Airlines & Aviation",
    "JetBlue Airways": "Airlines & Aviation",

    # --- International: Telecommunications ---
    "AT&T": "Telecommunications",
    "Verizon": "Telecommunications",
    "T-Mobile US": "Telecommunications",
    "Nokia": "Telecommunications",
    "Ericsson": "Telecommunications",

    # --- International: Real Estate (NEW sector, v1.3) ---
    "Prologis": "Real Estate",
    "American Tower": "Real Estate",
    "Equinix": "Real Estate",
    "Public Storage": "Real Estate",
    "Simon Property Group": "Real Estate",
    "Realty Income": "Real Estate",
    "Digital Realty Trust": "Real Estate",
    "Welltower": "Real Estate",
    "AvalonBay Communities": "Real Estate",
    "Equity Residential": "Real Estate",
    "Crown Castle": "Real Estate",

    # --- International: Materials & Mining (NEW sector, v1.3) ---
    "Linde plc": "Materials & Mining",
    "Air Products and Chemicals": "Materials & Mining",
    "Sherwin-Williams": "Materials & Mining",
    "Ecolab": "Materials & Mining",
    "Dow Inc": "Materials & Mining",
    "DuPont de Nemours": "Materials & Mining",
    "LyondellBasell Industries": "Materials & Mining",
    "Freeport-McMoRan": "Materials & Mining",
    "Newmont Corporation": "Materials & Mining",
    "Nucor Corporation": "Materials & Mining",
    "Vale": "Materials & Mining",
    "Rio Tinto": "Materials & Mining",
    "BHP Group": "Materials & Mining",
    "Glencore": "Materials & Mining",
    "Albemarle Corporation": "Materials & Mining",

    # --- Crypto ---
    "Bitcoin": "Cryptocurrency",
    "Ethereum": "Cryptocurrency",
    "Binance": "Cryptocurrency",
    "Coinbase": "Cryptocurrency",
    "Ripple": "Cryptocurrency",
    "Solana": "Cryptocurrency",
    "Cardano": "Cryptocurrency",
    "Dogecoin": "Cryptocurrency",
    "Polkadot": "Cryptocurrency",
    "Litecoin": "Cryptocurrency",
    "Avalanche": "Cryptocurrency",
    "Chainlink": "Cryptocurrency",
    "Polygon": "Cryptocurrency",
    "Shiba Inu": "Cryptocurrency",
    "Uniswap": "Cryptocurrency",
    "Toncoin": "Cryptocurrency",
    "Tron": "Cryptocurrency",
    "Cosmos": "Cryptocurrency",
    "Aave": "Cryptocurrency",
    "Near Protocol": "Cryptocurrency",
    "Internet Computer": "Cryptocurrency",
    "Stellar": "Cryptocurrency",
    "Monero": "Cryptocurrency",
    "Bitcoin Cash": "Cryptocurrency",
    "Algorand": "Cryptocurrency",
    "VeChain": "Cryptocurrency",
    "Filecoin": "Cryptocurrency",
    "The Graph": "Cryptocurrency",
    "Injective": "Cryptocurrency",
    "Sui": "Cryptocurrency",
    "Aptos": "Cryptocurrency",
    "Arbitrum": "Cryptocurrency",
    "Optimism": "Cryptocurrency",
    "Sei": "Cryptocurrency",
    "Celestia": "Cryptocurrency",
    "Pepe": "Cryptocurrency",
    "dYdX": "Cryptocurrency",
    "MakerDAO": "Cryptocurrency",
    "Curve DAO": "Cryptocurrency",
    "Fantom": "Cryptocurrency",
    "Hedera": "Cryptocurrency",
}

# Fallback keyword/phrase lists (English + Romanian) per sector, used
# ONLY when no known company was found in the article. Intentionally
# short and high-precision (whole words/phrases, not single generic
# words) to avoid noisy, low-confidence guesses.
SECTOR_KEYWORDS: Dict[str, List[str]] = {
    "Technology": [
        "technology", "software", "artificial intelligence",
        "semiconductor", "cloud computing", "tehnologie",
    ],
    "Energy": [
        "oil prices", "crude oil", "natural gas", "energy prices",
        "petrol", "energie electrica", "gaze naturale",
    ],
    "Financial Services": [
        "interest rate", "central bank", "mortgage rate",
        "banking sector", "dobanda cheie", "sistem bancar",
    ],
    "Healthcare": [
        "hospital", "pharmaceutical", "healthcare system",
        "spital", "sanatate publica",
    ],
    "Automotive": [
        "automaker", "electric vehicle", "car manufacturer",
        "masini electrice",
    ],
    "Telecommunications": [
        "telecom operator", "mobile network", "broadband",
        "telecomunicatii",
    ],
    "Cryptocurrency": [
        "cryptocurrency", "blockchain", "digital asset", "criptomoneda",
    ],
    "Utilities": [
        "power grid", "water utility", "electricity grid",
        "retea electrica",
    ],
    "Media & Entertainment": [
        "streaming service", "box office", "film studio",
    ],
    "Retail & E-commerce": [
        "online retailer", "e-commerce", "retail sales",
    ],
    "Real Estate": [
        "commercial real estate", "property market", "piata imobiliara",
    ],
    "Materials & Mining": [
        "mining industry", "commodity prices", "raw materials", "metale",
    ],
}
